name: CI

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        perl: ["5.14", "5.12", "5.16"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Update system and install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get -y install libhunspell-1.7-0 hunspell-en-us libhunspell-dev

    - name: Install Perl modules
      run: |
        cd Text-Hoborg
        cpanm ExtUtils::PkgConfig

    - name: Run tests
      run: |
        cd Text-Hoborg
        perl Makefile.PL && make test
